"""
One-shot helper: build manuscript.yaml from a draft .docx (paragraph order preserved).

Usage:
  python src/docx_to_manuscript.py "In Process/MyTopic/draft.docx" -o "In Process/MyTopic/manuscript.yaml"

Re-run after large edits to the Word file, or use the YAML as a starting point and edit by hand.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml
from docx import Document

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def extract_paragraphs(docx_path: Path) -> list[str]:
    doc = Document(str(docx_path))
    return [p.text.strip() for p in doc.paragraphs]


def build_manuscript_from_agentic_rag_doc(paras: list[str], *, output_stem: str) -> dict:
    """
    Section slices tuned for 'Research Paper Generation Request.docx' structure.
    Adjust indices in this function if you change the Word outline.
    """
    if len(paras) < 95:
        raise ValueError(f"Expected many paragraphs (got {len(paras)}); wrong document?")

    title = paras[0]
    abstract = paras[4]
    if paras[3].lower() != "abstract" or paras[5] != "Introduction":
        raise ValueError(
            "This doc does not match the expected outline (Abstract / Introduction). "
            "Edit docx_to_manuscript.py slice logic or use a generic exporter (future)."
        )

    sections = [
        {"heading": "1. Introduction", "paragraphs": [p for p in paras[6:10] if p]},
        {"heading": "2. Related Work", "paragraphs": [p for p in paras[11:18] if p]},
        {"heading": "3. Proposed System Architecture", "paragraphs": [p for p in paras[19:35] if p]},
        {"heading": "4. Data Storage and Indexing Strategies", "paragraphs": [p for p in paras[35:63] if p]},
        {"heading": "5. Orchestration and Reliability Mechanisms", "paragraphs": [p for p in paras[63:71] if p]},
        {"heading": "6. Performance and Human-Centric Analysis", "paragraphs": [p for p in paras[71:79] if p]},
        {"heading": "7. Discussion: Toward Orchestrated Distributed Intelligence", "paragraphs": [p for p in paras[79:83] if p]},
        {"heading": "8. Conclusions", "paragraphs": [p for p in paras[83:91] if p]},
    ]

    refs: list[str] = []
    if len(paras) > 92 and paras[91].lower().replace(" ", "") in ("workscited", "workscited.", "references"):
        start = 92
    else:
        start = 91
    for p in paras[start:]:
        if p:
            refs.append(p)

    return {
        "title": title,
        "author": "Mingwei Zhang",
        "affiliation": "Independent Researcher",
        "location": "Singapore",
        "date": "March 2026",
        "output_stem": output_stem,
        "abstract": abstract,
        "sections": sections,
        "references": refs,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Create manuscript.yaml from a .docx draft")
    parser.add_argument("docx", type=Path, help="Path to the Word document")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="Where to write manuscript.yaml (e.g. same folder as the docx)",
    )
    parser.add_argument(
        "--stem",
        default="Agentic_RAG_Three_Tier_Framework_March_2026",
        metavar="NAME",
        help="Value for output_stem in YAML (Published/ .docx base name)",
    )
    args = parser.parse_args()

    docx = args.docx.resolve() if not args.docx.is_absolute() else args.docx
    if not docx.is_file():
        print(f"Not found: {docx}", file=sys.stderr)
        return 2

    paras = extract_paragraphs(docx)
    try:
        data = build_manuscript_from_agentic_rag_doc(paras, output_stem=args.stem)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 2

    out = args.output.resolve() if not args.output.is_absolute() else args.output
    out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by docx_to_manuscript.py — edit freely. Re-run exporter if you reshape the Word outline.\n\n"
    )
    text = header + yaml.dump(
        data,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=1000,
    )
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out} ({len(data['sections'])} sections, {len(data['references'])} reference lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
